name: Deploy Project
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install
        working-directory: client
        
      - name: Build
        run: |
          touch .env
          echo 'REACT_APP_DEV_SERVER_URL=${{ secrets.DEV_SERVER_URL }}' >> .env
          echo 'GITHUB_OAUTH_CLIENT_ID=${{ secrets.OAUTH_GITHUB_CLIENT_ID }}' >> .env
          echo 'GITHUB_OAUTH_CLIENT_SECRET_KEY=${{ secrets.OAUTH_GITHUB_CLIENT_SECRET_KEY }}' >> .env
          echo 'APP_DOMAIN=${{ secrets.APP_DOMAIN }}' >> .env
          echo 'SENTRY_DSN=${{ secrets.SENTRY_DSN }}' >> .env
          echo 'ORIGIN_GRAPHQL=https://dev-answer.com/graphql'  >> .env
          yarn relay && yarn run build
        working-directory: client
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{secrets.PERSONAL_TOKEN}}
          PUBLISH_BRANCH: github-pages
          PUBLISH_DIR: ./client/dist
