name: Deploy Server

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/dev-answer
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pm2 save
            pm2 stop app
            sudo git pull
            cd server
            yarn
            yarn run production
